### ISSUE TITLE
Does not work on rails 5.1

### ISSUE THREAD

**Issue by JuliaUsanova** [marcosnogueira/jquery-slimscroll-rails#6]
```
jquery.slimscroll.min.self-ef4d19ff87aeed43da5cfa98d11109552a2497d5475d820effc123e6e55d4f9f.js?body=1:13 Uncaught TypeError: c.draggable is not a function
    at HTMLDivElement.<anonymous> (jquery.slimscroll.min.self-ef4d19ff87aeed43da5cfa98d11109552a2497d5475d820effc123e6e55d4f9f.js?body=1:13)
    at Function.each (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:363)
    at jQuery.fn.init.each (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:158)
    at jQuery.fn.init.slimScroll (jquery.slimscroll.min.self-ef4d19ff87aeed43da5cfa98d11109552a2497d5475d820effc123e6e55d4f9f.js?body=1:9)
    at initSidebarScroll (application.self-c88a5adecdb93c42d9c1a20a66c3c8f771ba866d397d27ff395ce4ad694020b8.js?body=1:36)
    at HTMLDocument.$.on (application.self-c88a5adecdb93c42d9c1a20a66c3c8f771ba866d397d27ff395ce4ad694020b8.js?body=1:26)
    at HTMLDocument.dispatch (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:5207)
    at HTMLDocument.elemData.handle (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:5015)
    at Object.Turbolinks.dispatch (turbolinks.self-2db6ec539b9190f75e1d477b305df53d12904d5cafdd47c7ffd91ba25cbec128.js?body=1:6)
    at e.notifyApplicationAfterPageLoad (turbolinks.self-2db6ec539b9190f75e1d477b305df53d12904d5cafdd47c7ffd91ba25cbec128.js?body=1:7)
```
